name: build
on:
    push:
        branches:
            - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use NodeJS 22
        uses: actions/setup-node@v5
        with:
            node-version: 22
      - name: Build PDF
        run: |
          npm ci
          npm run build
          mkdir build
          mv index.html cv.pdf style.css build/
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@1510b11c0c2f843eafb8ff41b3da8c467c8d4a9f
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
